#Naive Bayes Sınıflandırma Analizi Raporu
##1. Giriş ve Teorik Altyapı
Bu çalışma kapsamında, olasılıksal bir sınıflandırma algoritması olan Naive Bayes yöntemi kullanılarak veri kümesi üzerinde tahminleme yapılmıştır.
###1.1. Matris Manipülasyonu ve Makine Öğrenmesi İlişkisi
Makine öğrenmesinde veri setleri matris formunda ($X$ matrisi) temsil edilir.Satırlar: Her bir örneği temsil eder.Sütunlar: Her bir özelliği (feature) temsil eder.Naive Bayes algoritması, bu matris üzerindeki değerlerin istatistiksel dağılımını (ortalama, varyans) hesaplayarak çalışır.
###1.2. Özdeğer ve Özvektörlerin Rolü
Naive Bayes doğrudan özdeğer hesaplamasa da, veri setindeki özellikler arasında yüksek korelasyon olduğunda (çoklu doğrusallık), PCA (Temel Bileşenler Analizi) gibi özdeğer/özvektör tabanlı yöntemlerle boyut indirgeme yapılarak modelin performansı artırılabilir.
##2. Uygulama: Scikit-Learn ile Gaussian Naive Bayes
Aşağıdaki kod bloklarında, standart bir veri seti üzerinden model eğitimi ve performans değerlendirmesi yapılmıştır.

In [2]:
# Gerekli kütüphanelerin içe aktarılması
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.datasets import load_iris

# 1. Veri Setinin Yüklenmesi (Örnek: Iris Veri Seti)
iris = load_iris()
X = iris.data  # Özellik matrisi
y = iris.target # Hedef değişken

# 2. Verinin Eğitim ve Test olarak bölünmesi (%80 Eğitim, %20 Test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Modelin Oluşturulması ve Eğitilmesi
model = GaussianNB()
model.fit(X_train, y_train)

# 4. Tahmin Yapılması
y_pred = model.predict(X_test)

# 5. Performans Sonuçları
print("Karmaşıklık Matrisi (Confusion Matrix):")
print(confusion_matrix(y_test, y_pred))
print("\nSınıflandırma Raporu:")
print(classification_report(y_test, y_pred))
print(f"Doğruluk Skorunuz (Accuracy): {accuracy_score(y_test, y_pred) * 100:.2f}%")

Karmaşıklık Matrisi (Confusion Matrix):
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Sınıflandırma Raporu:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Doğruluk Skorunuz (Accuracy): 100.00%


##3. Sonuç ve Değerlendirme
Yapılan analiz sonucunda Naive Bayes algoritmasının, özellikle özelliklerin birbirinden bağımsız varsayıldığı durumlarda oldukça hızlı ve etkili sonuçlar verdiği gözlemlenmiştir. Modelin başarısı, veri matrisinin doğru manipüle edilmesi ve eğitim sürecindeki istatistiksel hesaplamaların doğruluğu ile doğrudan ilişkilidir.

## Kaynakça
1. Scikit-Learn Documentation. "Naive Bayes Classifiers". [scikit-learn.org](https://scikit-learn.org/stable/modules/naive_bayes.html)
2. Brownlee, J. "A Gentle Introduction to Bayes' Theorem for Machine Learning". Machine Learning Mastery.
3. Bishop, C. M. "Pattern Recognition and Machine Learning". Springer.